In [1]:
import pandas as pd
import tabula

In [2]:
# extracting table from pdf using tabula

df = tabula.read_pdf('RMS-EKM-to upload.pdf',pages='1',lattice=True)

df

[    Permit Number :7/2971/2006\rPermit Owner:SRI ELDHO PAUL\rPermit Owner Address: PARAKKAL HOUSE MEKKAD P.O.,THURUTHUSSERRY.\rPermit Valid From:\rPermit Mobile:\rVehicle Number :KL 05 V 3702\rVehicle Owner Name:SRI ELDHO PAUL\rVehicle Owner Address: PARAKKAL HOUSE MEKKAD P.O.,THURUTHUSSERRY.\rPermit Valid To: 18/09/2016\rRTO : KL-07 Ernakulam\rTrip Day ANGAMALY PRIVATE BUS STATIONATHANIMANJALYNORTH PARAVUR\rADViaAD ViaADViaADVia\r1106:35 am06:53 am07:15 am07:25 am\r2108:20 am08:02 am07:40 am07:30 am\r3108:38 am08:56 am09:18 am09:28 am\r4111:01 am10:43 am10:21 am10:11 am\r5111:04 am11:22 am11:44 am11:54 am\r6101:27 pm01:09 pm12:47 pm12:37 pm\r7101:52 pm02:10 pm02:32 pm02:42 pm\r8103:35 pm03:27 pm03:05 pm02:55 pm\r9104:05 pm04:23 pm04:45 pm04:55 pm\r10106:17 pm05:59 pm05:35 pm 05:37 pm05:25 pm\r11106:52 pm07:10 pm07:32 pm07:42 pm\r12109:05 pm08:47 pm08:25 pm08:15 pm\rThis digital copy of permit is used for the verification of permit and time sheet details of KL-07 Ernakulam RTO\rെപാ ജന താൽപര ാർഥം സി ീകരിത്.സമയ വിവര പ ികയിൽ ആേപപം ആർ.ടി. ഓഫീസിൽ ബെഅധികാരി് സമം സമർ ി ാതാണ്.  \
 0                                                 NaN
 1                                                 NaN
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 5                                                 NaN
 6                                                 NaN
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN
 13                                                NaN

    Unnamed: 0  Unnamed: 1 Unnamed: 2  Unnamed: 3  \
 0        Trip         NaN        Day         NaN
 1         NaN         NaN        NaN         NaN
 2           1         NaN          1         NaN
 3           2         NaN          1         NaN
 4           3         NaN          1         NaN
 5           4         NaN          1         NaN
 6           5         NaN          1         NaN
 7           6         NaN          1         NaN
 8           7         NaN          1         NaN
 9           8         NaN          1         NaN
 10          9         NaN          1         NaN
 11         10         NaN          1         NaN
 12         11         NaN          1         NaN
 13         12         NaN          1         NaN

                       Unnamed: 4  Unnamed: 5 Unnamed: 6  Unnamed: 7  \
 0   ANGAMALY PRIVATE BUS STATION         NaN     ATHANI         NaN
 1                              A         NaN          D         NaN
 2                            NaN         NaN   06:35 am         NaN
 3                       08:20 am         NaN        NaN         NaN
 4                            NaN         NaN   08:38 am         NaN
 5                       11:01 am         NaN        NaN         NaN
 6                            NaN         NaN   11:04 am         NaN
 7                       01:27 pm         NaN        NaN         NaN
 8                            NaN         NaN   01:52 pm         NaN
 9                       03:35 pm         NaN        NaN         NaN
 10                           NaN         NaN   04:05 pm         NaN
 11                      06:17 pm         NaN        NaN         NaN
 12                           NaN         NaN   06:52 pm         NaN
 13                      09:05 pm         NaN        NaN         NaN

    Unnamed: 8  ...  Unnamed: 18 Unnamed: 19  Unnamed: 20 Unnamed: 21  \
 0     MANJALY  ...          NaN         NaN          NaN         NaN
 1         Via  ...            D         NaN          Via         NaN
 2         NaN  ...          NaN         NaN          NaN         NaN
 3         NaN  ...          NaN         NaN          NaN         NaN
 4         NaN  ...          NaN         NaN          NaN         NaN
 5         NaN  ...          NaN         NaN          NaN         NaN
 6         NaN  ...          NaN         NaN          NaN         NaN
 7         NaN  ...          NaN         NaN          NaN         NaN
 8         NaN  ...          NaN         NaN          NaN         NaN
 9         NaN  ...          NaN         NaN          NaN         NaN
 10        NaN  ...          NaN         NaN          NaN         NaN
 11        NaN  ...     05:37 pm         NaN          NaN         NaN
 12        NaN  ...          NaN         NaN          NaN         NaN
 13        NaN  ...          NaN         NaN          NaN         NaN

     Unnamed: 22 Unnamed: 23  Unnamed: 24 Unnamed: 25  Unnamed: 26 Unnamed: 27
 0           NaN         NaN          NaN         NaN          NaN         NaN
 1             A         NaN            D         NaN          Via         NaN
 2      07:25 am         NaN          NaN         NaN          NaN         NaN
 3           NaN         NaN     07:30 am         NaN          NaN         NaN
 4      09:28 am         NaN          NaN         NaN          NaN         NaN
 5           NaN         NaN     10:11 am         NaN          NaN         NaN
 6      11:54 am         NaN          NaN         NaN          NaN         NaN
 7           NaN         NaN     12:37 pm         NaN          NaN         NaN
 8      02:42 pm         NaN          NaN         NaN          NaN         NaN
 9           NaN         NaN     02:55 pm         NaN          NaN         NaN
 10     04:55 pm         NaN          NaN         NaN          NaN         NaN
 11          NaN         NaN     05:25 pm         NaN          NaN         NaN
 12     07:42 pm         NaN          NaN         NaN          NaN         NaN
 13          NaN         NaN     08:15 pm         NaN          NaN         NaN

 [14 rows x 29 columns],
     Permit Number :7/2971/2006\rPermit Owner:SRI ELDHO PAUL\rPermit Owner Address: PARAKKAL HOUSE MEKKAD P.O.,THURUTHUSSERRY.\rPermit Valid From:\rPermit Mobile:\rVehicle Number :KL 05 V 3702\rVehicle Owner Name:SRI ELDHO PAUL\rVehicle Owner Address: PARAKKAL HOUSE MEKKAD P.O.,THURUTHUSSERRY.\rPermit Valid To: 18/09/2016\rRTO : KL-07 Ernakulam\rTrip Day ANGAMALY PRIVATE BUS STATIONATHANIMANJALYNORTH PARAVUR\rADViaAD ViaADViaADVia\r1106:35 am06:53 am07:15 am07:25 am\r2108:20 am08:02 am07:40 am07:30 am\r3108:38 am08:56 am09:18 am09:28 am\r4111:01 am10:43 am10:21 am10:11 am\r5111:04 am11:22 am11:44 am11:54 am\r6101:27 pm01:09 pm12:47 pm12:37 pm\r7101:52 pm02:10 pm02:32 pm02:42 pm\r8103:35 pm03:27 pm03:05 pm02:55 pm\r9104:05 pm04:23 pm04:45 pm04:55 pm\r10106:17 pm05:59 pm05:35 pm 05:37 pm05:25 pm\r11106:52 pm07:10 pm07:32 pm07:42 pm\r12109:05 pm08:47 pm08:25 pm08:15 pm\rThis digital copy of permit is used for the verification of permit and time sheet details of KL-07 Ernakulam RTO\rെപാ ജന താൽപര ാർഥം സി ീകരിത്.സമയ വിവര പ ികയിൽ ആേപപം ആർ.ടി. ഓഫീസിൽ ബെഅധികാരി് സമം സമർ ി ാതാണ്.  \
 0                                                 NaN
 1                                                 NaN
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 5                                                 NaN
 6                                                 NaN
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN
 13                                                NaN

    Unnamed: 0  Unnamed: 1 Unnamed: 2  Unnamed: 3  \
 0        Trip         NaN        Day         NaN
 1         NaN         NaN        NaN         NaN
 2           1         NaN          1         NaN
 3           2         NaN          1         NaN
 4           3         NaN          1         NaN
 5           4         NaN          1         NaN
 6           5         NaN          1         NaN
 7           6         NaN          1         NaN
 8           7         NaN          1         NaN
 9           8         NaN          1         NaN
 10          9         NaN          1         NaN
 11         10         NaN          1         NaN
 12         11         NaN          1         NaN
 13         12         NaN          1         NaN

                       Unnamed: 4  Unnamed: 5 Unnamed: 6  Unnamed: 7  \
 0   ANGAMALY PRIVATE BUS STATION         NaN     ATHANI         NaN
 1                              A         NaN          D         NaN
 2                            NaN         NaN   06:35 am         NaN
 3                       08:20 am         NaN        NaN         NaN
 4                            NaN         NaN   08:38 am         NaN
 5                       11:01 am         NaN        NaN         NaN
 6                            NaN         NaN   11:04 am         NaN
 7                       01:27 pm         NaN        NaN         NaN
 8                            NaN         NaN   01:52 pm         NaN
 9                       03:35 pm         NaN        NaN         NaN
 10                           NaN         NaN   04:05 pm         NaN
 11                      06:17 pm         NaN        NaN         NaN
 12                           NaN         NaN   06:52 pm         NaN
 13                      09:05 pm         NaN        NaN         NaN

    Unnamed: 8  ...  Unnamed: 18 Unnamed: 19  Unnamed: 20 Unnamed: 21  \
 0     MANJALY  ...          NaN         NaN          NaN         NaN
 1         Via  ...            D         NaN          Via         NaN
 2         NaN  ...          NaN         NaN          NaN         NaN
 3         NaN  ...          NaN         NaN          NaN         NaN
 4         NaN  ...          NaN         NaN          NaN         NaN
 5         NaN  ...          NaN         NaN          NaN         NaN
 6         NaN  ...          NaN         NaN          NaN         NaN
 7         NaN  ...          NaN         NaN          NaN         NaN
 8         NaN  ...          NaN         NaN          NaN         NaN
 9         NaN  ...          NaN         NaN          NaN         NaN
 10        NaN  ...          NaN         NaN          NaN         NaN
 11        NaN  ...     05:37 pm         NaN          NaN         NaN
 12        NaN  ...          NaN         NaN          NaN         NaN
 13        NaN  ...          NaN         NaN          NaN         NaN

     Unnamed: 22 Unnamed: 23  Unnamed: 24 Unnamed: 25  Unnamed: 26 Unnamed: 27
 0           NaN         NaN          NaN         NaN          NaN         NaN
 1             A         NaN            D         NaN          Via         NaN
 2      07:25 am         NaN          NaN         NaN          NaN         NaN
 3           NaN         NaN     07:30 am         NaN          NaN         NaN
 4      09:28 am         NaN          NaN         NaN          NaN         NaN
 5           NaN         NaN     10:11 am         NaN          NaN         NaN
 6      11:54 am         NaN          NaN         NaN          NaN         NaN
 7           NaN         NaN     12:37 pm         NaN          NaN         NaN
 8      02:42 pm         NaN          NaN         NaN          NaN         NaN
 9           NaN         NaN     02:55 pm         NaN          NaN         NaN
 10     04:55 pm         NaN          NaN         NaN          NaN         NaN
 11          NaN         NaN     05:25 pm         NaN          NaN         NaN
 12     07:42 pm         NaN          NaN         NaN          NaN         NaN
 13          NaN         NaN     08:15 pm         NaN          NaN         NaN

 [14 rows x 29 columns]]

In [3]:
df[0]

,"Permit Number :7/2971/2006\rPermit Owner:SRI ELDHO PAUL\rPermit Owner Address: PARAKKAL HOUSE MEKKAD P.O.,THURUTHUSSERRY.\rPermit Valid From:\rPermit Mobile:\rVehicle Number :KL 05 V 3702\rVehicle Owner Name:SRI ELDHO PAUL\rVehicle Owner Address: PARAKKAL HOUSE MEKKAD P.O.,THURUTHUSSERRY.\rPermit Valid To: 18/09/2016\rRTO : KL-07 Ernakulam\rTrip Day ANGAMALY PRIVATE BUS STATIONATHANIMANJALYNORTH PARAVUR\rADViaAD ViaADViaADVia\r1106:35 am06:53 am07:15 am07:25 am\r2108:20 am08:02 am07:40 am07:30 am\r3108:38 am08:56 am09:18 am09:28 am\r4111:01 am10:43 am10:21 am10:11 am\r5111:04 am11:22 am11:44 am11:54 am\r6101:27 pm01:09 pm12:47 pm12:37 pm\r7101:52 pm02:10 pm02:32 pm02:42 pm\r8103:35 pm03:27 pm03:05 pm02:55 pm\r9104:05 pm04:23 pm04:45 pm04:55 pm\r10106:17 pm05:59 pm05:35 pm 05:37 pm05:25 pm\r11106:52 pm07:10 pm07:32 pm07:42 pm\r12109:05 pm08:47 pm08:25 pm08:15 pm\rThis digital copy of permit is used for the verification of permit and time sheet details of KL-07 Ernakulam RTO\rെപാ ജന താൽപര ാർഥം സി ീകരിത്.സമയ വിവര പ ികയിൽ ആേപപം ആർ.ടി. ഓഫീസിൽ ബെഅധികാരി് സമം സമർ ി ാതാണ്.",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,NaN,Trip,NaN,Day,NaN,ANGAMALY PRIVATE BUS STATION,NaN,ATHANI,NaN,MANJALY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,A,NaN,D,NaN,Via,...,D,NaN,Via,NaN,A,NaN,D,NaN,Via,NaN
2,NaN,1,NaN,1,NaN,NaN,NaN,06:35 am,NaN,NaN,...,NaN,NaN,NaN,NaN,07:25 am,NaN,NaN,NaN,NaN,NaN
3,NaN,2,NaN,1,NaN,08:20 am,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,07:30 am,NaN,NaN,NaN
4,NaN,3,NaN,1,NaN,NaN,NaN,08:38 am,NaN,NaN,...,NaN,NaN,NaN,NaN,09:28 am,NaN,NaN,NaN,NaN,NaN
5,NaN,4,NaN,1,NaN,11:01 am,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,10:11 am,NaN,NaN,NaN
6,NaN,5,NaN,1,NaN,NaN,NaN,11:04 am,NaN,NaN,...,NaN,NaN,NaN,NaN,11:54 am,NaN,NaN,NaN,NaN,NaN
7,NaN,6,NaN,1,NaN,01:27 pm,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12:37 pm,NaN,NaN,NaN
8,NaN,7,NaN,1,NaN,NaN,NaN,01:52 pm,NaN,NaN,...,NaN,NaN,NaN,NaN,02:42 pm,NaN,NaN,NaN,NaN,NaN
9,NaN,8,NaN,1,NaN,03:35 pm,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,02:55 pm,NaN,NaN,NaN
10,NaN,9,NaN,1,NaN,NaN,NaN,04:05 pm,NaN,NaN,...,NaN,NaN,NaN,NaN,04:55 pm,NaN,NaN,NaN,NaN,NaN
11,NaN,10,NaN,1,NaN,06:17 pm,NaN,NaN,NaN,NaN,...,05:37 pm,NaN,NaN,NaN,NaN,NaN,05:25 pm,NaN,NaN,NaN
12,NaN,11,NaN,1,NaN,NaN,NaN,06:52 pm,NaN,NaN,...,NaN,NaN,NaN,NaN,07:42 pm,NaN,NaN,NaN,NaN,NaN
13,NaN,12,NaN,1,NaN,09:05 pm,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,08:15 pm,NaN,NaN,NaN

In [4]:
# somehow the extraction contains a list of two duplicated dataframes of the table. Therefore selecting the first element of the list.

df = df[0]

In [5]:
# the dataframe contains a lot of noise, for e.g., null columns with no headers. So dropping them.

df = df.dropna(axis=1,how='all')

df

,Unnamed: 0,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14,Unnamed: 16,Unnamed: 18,Unnamed: 20,Unnamed: 22,Unnamed: 24,Unnamed: 26
0,Trip,Day,ANGAMALY PRIVATE BUS STATION,ATHANI,MANJALY,NORTH PARAVUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,A,D,Via,A,D,Via,A,D,Via,A,D,Via
2,1,1,NaN,06:35 am,NaN,06:53 am,NaN,NaN,07:15 am,NaN,NaN,07:25 am,NaN,NaN
3,2,1,08:20 am,NaN,NaN,08:02 am,NaN,NaN,07:40 am,NaN,NaN,NaN,07:30 am,NaN
4,3,1,NaN,08:38 am,NaN,08:56 am,NaN,NaN,09:18 am,NaN,NaN,09:28 am,NaN,NaN
5,4,1,11:01 am,NaN,NaN,10:43 am,NaN,NaN,10:21 am,NaN,NaN,NaN,10:11 am,NaN
6,5,1,NaN,11:04 am,NaN,11:22 am,NaN,NaN,11:44 am,NaN,NaN,11:54 am,NaN,NaN
7,6,1,01:27 pm,NaN,NaN,01:09 pm,NaN,NaN,12:47 pm,NaN,NaN,NaN,12:37 pm,NaN
8,7,1,NaN,01:52 pm,NaN,02:10 pm,NaN,NaN,02:32 pm,NaN,NaN,02:42 pm,NaN,NaN
9,8,1,03:35 pm,NaN,NaN,03:27 pm,NaN,NaN,03:05 pm,NaN,NaN,NaN,02:55 pm,NaN
10,9,1,NaN,04:05 pm,NaN,04:23 pm,NaN,NaN,04:45 pm,NaN,NaN,04:55 pm,NaN,NaN
11,10,1,06:17 pm,NaN,NaN,05:59 pm,NaN,NaN,05:35 pm,05:37 pm,NaN,NaN,05:25 pm,NaN
12,11,1,NaN,06:52 pm,NaN,07:10 pm,NaN,NaN,07:32 pm,NaN,NaN,07:42 pm,NaN,NaN
13,12,1,09:05 pm,NaN,NaN,08:47 pm,NaN,NaN,08:25 pm,NaN,NaN,NaN,08:15 pm,NaN

In [6]:
# the column header has shifted to the first row and sub-header to the second row. 

# edit: also it was noticed the final data contained '\r' in both columns and data. So removing it from the dataframe.

df = df.replace('\r',' ',regex=True)

In [7]:
# Extracting the names of the places from first row (header row). Removing 'Trip','Day', and null value

lst_places = list(df.loc[0,:].dropna().unique())

lst_places

['Trip',
 'Day',
 'ANGAMALY PRIVATE BUS STATION',
 'ATHANI',
 'MANJALY',
 'NORTH PARAVUR']

In [8]:
for i in ['Trip','Day']:
    if i in lst_places:
        lst_places.remove(i)

lst_places

['ANGAMALY PRIVATE BUS STATION', 'ATHANI', 'MANJALY', 'NORTH PARAVUR']

In [9]:
# extracting only the body of the data as dataframe since the headers and sub-headers are messed up.
# we don't need 'Trip' column since we already have the index

df = df.iloc[2:,1:]

df

,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14,Unnamed: 16,Unnamed: 18,Unnamed: 20,Unnamed: 22,Unnamed: 24,Unnamed: 26
2,1,NaN,06:35 am,NaN,06:53 am,NaN,NaN,07:15 am,NaN,NaN,07:25 am,NaN,NaN
3,1,08:20 am,NaN,NaN,08:02 am,NaN,NaN,07:40 am,NaN,NaN,NaN,07:30 am,NaN
4,1,NaN,08:38 am,NaN,08:56 am,NaN,NaN,09:18 am,NaN,NaN,09:28 am,NaN,NaN
5,1,11:01 am,NaN,NaN,10:43 am,NaN,NaN,10:21 am,NaN,NaN,NaN,10:11 am,NaN
6,1,NaN,11:04 am,NaN,11:22 am,NaN,NaN,11:44 am,NaN,NaN,11:54 am,NaN,NaN
7,1,01:27 pm,NaN,NaN,01:09 pm,NaN,NaN,12:47 pm,NaN,NaN,NaN,12:37 pm,NaN
8,1,NaN,01:52 pm,NaN,02:10 pm,NaN,NaN,02:32 pm,NaN,NaN,02:42 pm,NaN,NaN
9,1,03:35 pm,NaN,NaN,03:27 pm,NaN,NaN,03:05 pm,NaN,NaN,NaN,02:55 pm,NaN
10,1,NaN,04:05 pm,NaN,04:23 pm,NaN,NaN,04:45 pm,NaN,NaN,04:55 pm,NaN,NaN
11,1,06:17 pm,NaN,NaN,05:59 pm,NaN,NaN,05:35 pm,05:37 pm,NaN,NaN,05:25 pm,NaN
12,1,NaN,06:52 pm,NaN,07:10 pm,NaN,NaN,07:32 pm,NaN,NaN,07:42 pm,NaN,NaN
13,1,09:05 pm,NaN,NaN,08:47 pm,NaN,NaN,08:25 pm,NaN,NaN,NaN,08:15 pm,NaN

In [10]:
# index is corrected so as to start from 0.

df.index-=2

df

,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14,Unnamed: 16,Unnamed: 18,Unnamed: 20,Unnamed: 22,Unnamed: 24,Unnamed: 26
0,1,NaN,06:35 am,NaN,06:53 am,NaN,NaN,07:15 am,NaN,NaN,07:25 am,NaN,NaN
1,1,08:20 am,NaN,NaN,08:02 am,NaN,NaN,07:40 am,NaN,NaN,NaN,07:30 am,NaN
2,1,NaN,08:38 am,NaN,08:56 am,NaN,NaN,09:18 am,NaN,NaN,09:28 am,NaN,NaN
3,1,11:01 am,NaN,NaN,10:43 am,NaN,NaN,10:21 am,NaN,NaN,NaN,10:11 am,NaN
4,1,NaN,11:04 am,NaN,11:22 am,NaN,NaN,11:44 am,NaN,NaN,11:54 am,NaN,NaN
5,1,01:27 pm,NaN,NaN,01:09 pm,NaN,NaN,12:47 pm,NaN,NaN,NaN,12:37 pm,NaN
6,1,NaN,01:52 pm,NaN,02:10 pm,NaN,NaN,02:32 pm,NaN,NaN,02:42 pm,NaN,NaN
7,1,03:35 pm,NaN,NaN,03:27 pm,NaN,NaN,03:05 pm,NaN,NaN,NaN,02:55 pm,NaN
8,1,NaN,04:05 pm,NaN,04:23 pm,NaN,NaN,04:45 pm,NaN,NaN,04:55 pm,NaN,NaN
9,1,06:17 pm,NaN,NaN,05:59 pm,NaN,NaN,05:35 pm,05:37 pm,NaN,NaN,05:25 pm,NaN
10,1,NaN,06:52 pm,NaN,07:10 pm,NaN,NaN,07:32 pm,NaN,NaN,07:42 pm,NaN,NaN
11,1,09:05 pm,NaN,NaN,08:47 pm,NaN,NaN,08:25 pm,NaN,NaN,NaN,08:15 pm,NaN

In [11]:
# rebuilding the headers and sub-headers using the list_places and MultiIndexing 
# added an empty element with 'Day' since multiindexing columns requires every header to have same no. of levels

lst_subheader = ['A','D','Via']

lst_columns = [('Day','')]

for i in lst_places:
    for j in lst_subheader:
        lst_columns.append((i,j))
        
lst_columns

[('Day', ''),
 ('ANGAMALY PRIVATE BUS STATION', 'A'),
 ('ANGAMALY PRIVATE BUS STATION', 'D'),
 ('ANGAMALY PRIVATE BUS STATION', 'Via'),
 ('ATHANI', 'A'),
 ('ATHANI', 'D'),
 ('ATHANI', 'Via'),
 ('MANJALY', 'A'),
 ('MANJALY', 'D'),
 ('MANJALY', 'Via'),
 ('NORTH PARAVUR', 'A'),
 ('NORTH PARAVUR', 'D'),
 ('NORTH PARAVUR', 'Via')]

In [12]:
df_copy = df.copy()
df_copy.columns = pd.MultiIndex.from_tuples(lst_columns)

df_copy

   Day ANGAMALY PRIVATE BUS STATION                   ATHANI            \
                                  A         D  Via         A    D  Via
0    1                          NaN  06:35 am  NaN  06:53 am  NaN  NaN
1    1                     08:20 am       NaN  NaN  08:02 am  NaN  NaN
2    1                          NaN  08:38 am  NaN  08:56 am  NaN  NaN
3    1                     11:01 am       NaN  NaN  10:43 am  NaN  NaN
4    1                          NaN  11:04 am  NaN  11:22 am  NaN  NaN
5    1                     01:27 pm       NaN  NaN  01:09 pm  NaN  NaN
6    1                          NaN  01:52 pm  NaN  02:10 pm  NaN  NaN
7    1                     03:35 pm       NaN  NaN  03:27 pm  NaN  NaN
8    1                          NaN  04:05 pm  NaN  04:23 pm  NaN  NaN
9    1                     06:17 pm       NaN  NaN  05:59 pm  NaN  NaN
10   1                          NaN  06:52 pm  NaN  07:10 pm  NaN  NaN
11   1                     09:05 pm       NaN  NaN  08:47 pm  NaN  NaN

     MANJALY                NORTH PARAVUR
           A         D  Via             A         D  Via
0   07:15 am       NaN  NaN      07:25 am       NaN  NaN
1   07:40 am       NaN  NaN           NaN  07:30 am  NaN
2   09:18 am       NaN  NaN      09:28 am       NaN  NaN
3   10:21 am       NaN  NaN           NaN  10:11 am  NaN
4   11:44 am       NaN  NaN      11:54 am       NaN  NaN
5   12:47 pm       NaN  NaN           NaN  12:37 pm  NaN
6   02:32 pm       NaN  NaN      02:42 pm       NaN  NaN
7   03:05 pm       NaN  NaN           NaN  02:55 pm  NaN
8   04:45 pm       NaN  NaN      04:55 pm       NaN  NaN
9   05:35 pm  05:37 pm  NaN           NaN  05:25 pm  NaN
10  07:32 pm       NaN  NaN      07:42 pm       NaN  NaN
11  08:25 pm       NaN  NaN           NaN  08:15 pm  NaN

In [13]:
# we have created our dataframe.

# a mutliindexed dataframe with multiple column levels converted into a dictionary will have tuple keys.
# unfortunately dict with tuple keys do not convert well to JSON since we have to convert it back to dataframe
# therefore skip the multiindexing step and find a solution to building a dictionary apt to be converted to JSON

In [14]:
# a dictionary will be created with 'Day'+places as keys and each place having a value:dict containing 'A','D','Via' as keys
# inturn 'A','D','Via' will have values:list(columnwise data)

In [15]:
dict1 = {
    'Day':list(df.iloc[:,0])
}

dict1

{'Day': ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']}

In [16]:
column_number=1
for i in lst_places:
    dict2={}
    for j in ['A','D','Via']:
        values = df.iloc[:,column_number]
        
        # edit: the time data was found to have '.' instead of ':'
        if j=='A' or j=='D':
            values = values.str.replace('.',':')
        dict2[j]=list(values)
        column_number+=1
        dict1[i]=dict2

dict1

{'Day': ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
 'ANGAMALY PRIVATE BUS STATION': {'A': [nan,
   '08:20 am',
   nan,
   '11:01 am',
   nan,
   '01:27 pm',
   nan,
   '03:35 pm',
   nan,
   '06:17 pm',
   nan,
   '09:05 pm'],
  'D': ['06:35 am',
   nan,
   '08:38 am',
   nan,
   '11:04 am',
   nan,
   '01:52 pm',
   nan,
   '04:05 pm',
   nan,
   '06:52 pm',
   nan],
  'Via': [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]},
 'ATHANI': {'A': ['06:53 am',
   '08:02 am',
   '08:56 am',
   '10:43 am',
   '11:22 am',
   '01:09 pm',
   '02:10 pm',
   '03:27 pm',
   '04:23 pm',
   '05:59 pm',
   '07:10 pm',
   '08:47 pm'],
  'D': [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
  'Via': [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]},
 'MANJALY': {'A': ['07:15 am',
   '07:40 am',
   '09:18 am',
   '10:21 am',
   '11:44 am',
   '12:47 pm',
   '02:32 pm',
   '03:05 pm',
   '04:45 pm',
   '05:35 pm',
   '07:32 pm',
   '08:25 pm'],
  'D': [nan, nan, nan, nan, nan, nan, nan, nan, nan, '05:37 pm', nan, nan],
  'Via': [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]},
 'NORTH PARAVUR': {'A': ['07:25 am',
   nan,
   '09:28 am',
   nan,
   '11:54 am',
   nan,
   '02:42 pm',
   nan,
   '04:55 pm',
   nan,
   '07:42 pm',
   nan],
  'D': [nan,
   '07:30 am',
   nan,
   '10:11 am',
   nan,
   '12:37 pm',
   nan,
   '02:55 pm',
   nan,
   '05:25 pm',
   nan,
   '08:15 pm'],
  'Via': [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]}}

In [17]:
# converting and exporting dict1 as JSON file

import json

with open("output.json", "w") as outfile: 
    json.dump(dict1, outfile)